insert into airline values(null, "RianAir", 61, "Johannes", "Adami");
insert into airline values(null, "Lufthansa", 62, "Julia", "Biechl");
insert into airline values(null, "Turkish Airlines", 63, "Eva", "Bobchev");
insert into airline values(null, "EasyJet", 64, "Oliver", "Brandstetter");
insert into airline values(null, "Aire6plore", 65, "David", "Cech");
insert into airline values(null, "Air France", 66, "Daniel", "Egger");
insert into airline values(null, "Air India", 67, "Feli6", "Haider");
insert into airline values(null, "Airlink", 68, "Ian", "Hirschuber");
insert into airline values(null, "Alpine Flight Service", 69, "Sebastian", "Karamatic");
insert into airline values(null, "Bluebird Nordic", 70, "Tobias", "Felder");
insert into airline values(null, "British Airways", 71, "Pavel", "Kakhluv");
insert into airline values(null, "China Airlines", 72, "Patrik", "Klaric");
insert into airline values(null, "Fly Egypt", 73, "Simon", "Gwercher");
insert into airline values(null, "Hahn Airlines", 74, "Jonathan", "Gendu");
insert into airline values(null, "Interjet", 75, "Kirchmair", "Jonas");
insert into airline values(null, "JetConnect", 76, "Burak", "Kocak");
insert into airline values(null, "Libyan Airlines", 77, "Noah", "Salzer (RIP)");
insert into airline values(null, "Mali Air", 78, "Ege", "Tuncel");
insert into airline values(null, "North Flying", 79, "Tim", "Steuxner");
insert into airline values(null, "Orange2fly", 80, "Florian", "Peer");
