insert into airline values(null, "RianAir", x, "Johannes", "Adami");
insert into airline values(null, "Lufthansa", x, "Julia", "Biechl");
insert into airline values(null, "Turkish Airlines", x, "Eva", "Bobchev");
insert into airline values(null, "EasyJet", x, "Oliver", "Brandstetter");
insert into airline values(null, "Airexplore", x, "David", "Cech");
insert into airline values(null, "Air France", x, "Daniel", "Egger");
insert into airline values(null, "Air India", x, "Felix", "Haider");
insert into airline values(null, "Airlink", x, "Ian", "Hirschuber");
insert into airline values(null, "Alpine Flight Service", x, "Sebastian", "Karamatic");
insert into airline values(null, "Bluebird Nordic", x, "Tobias", "Felder");
insert into airline values(null, "British Airways", x, "Pavel", "Kakhluv");
insert into airline values(null, "China Airlines", x, "Patrik", "Klaric");
insert into airline values(null, "Fly Egypt", x, "Simon", "Gwercher");
insert into airline values(null, "Hahn Airlines", x, "Jonathan", "Gendu");
insert into airline values(null, "Interjet", x, "Kirchmair", "Jonas");
insert into airline values(null, "JetConnect", x, "Burak", "Kocak");
insert into airline values(null, "Libyan Airlines", x, "Noah", "Salzer (RIP)");
insert into airline values(null, "Mali Air", x, "Ege", "Tuncel");
insert into airline values(null, "North Flying", x, "Tim", "Steuxner");
insert into airline values(null, "Orange2fly", x, "Florian", "Peer");
insert into airline values(null, "Royal Jordanian", x, "Maximilian", "Stebler");
insert into airline values(null, "Shanghai Airlines", x, "Lara", "Marthe");
insert into airline values(null, "Sunexpress", x, "Stefan", "Mallaun");
insert into airline values(null, "Wamos Air", x, "Daniel", "Kopp");
insert into airline values(null, "Zorex", x, "David", "Mark");